### ISSUE TITLE
How to GetComponent of GameObject

### ISSUE THREAD

**Issue by whitespeed** [karolwieczorek/Unity_PythonConsole#1]
I try to get rigidbody and collider of a gameobject, but gotten a error like it.
![image](https://user-images.githubusercontent.com/5187837/54109304-442a3a00-4419-11e9-91ea-d3aba07842cd.png)
However when I get LineRenderer, that is ok.
![image](https://user-images.githubusercontent.com/5187837/54109406-86537b80-4419-11e9-9f4c-457abff6ce0c.png)

**Comment by karolwieczorek** [comment]
Try 
```
import clr
clr.AddReference("UnityEngine.PhysicsModule")
rigid = a.GetComponent[UnityEngine.Rigidbody]();
print rigid.mass
```

**Comment by whitespeed** [comment]
Thanks for reply.  I fixed it after upgrading IronPython.
